Initial noble support

diff --git a/src/app/qml/bin/jerk-installer/jerk b/src/app/qml/bin/jerk-installer/jerk
--- a/src/app/qml/bin/jerk-installer/jerk
+++ b/src/app/qml/bin/jerk-installer/jerk
@@ -20,7 +20,7 @@ SYSTEM_ARCH="$(uname -m)"
 RAN_AS_SUDO=0
 
 # Constant values
-VERSION="1.0.8"
+VERSION="1.0.10"
 BACKUP_SUFFIX=".JERKORIG"
 ORIG_FOLDERNAME="ORIG"
 MOD_FOLDERNAME="MOD"
@@ -189,6 +189,20 @@ function remountRootfsROIfNecessary
     fi
 }
 
+# Check if file is empty
+# 0 if not, 1 if empty
+function checkFileIfEmpty
+{
+    local return_code=0
+    local filename=$1
+
+    if [ ! -s "$filename" ]; then
+        return_code=1
+    fi
+
+    return $return_code
+}
+
 # Put MOD and ORIG files into arrays
 function listFiles
 {
@@ -292,11 +306,18 @@ function validateInput
                                     TARGET_PATH=$(echo $focal_target_path | sed 's/\/$//') # Last "/" is removed if there's any
                                 fi
                                 ;;
-                            *)
-                                if [ "$SYSTEM_ARCH" != "aarch64" ] && [[ -v armhf_target_path ]]; then # If armhf (32-bit) and has config for it
-                                    TARGET_PATH=$(echo $armhf_focal_target_path | sed 's/\/$//')
+                            "24.04")
+                                if [ "$SYSTEM_ARCH" != "aarch64" ] && [[ -v armhf_noble_target_path ]]; then # If armhf (32-bit) and has config for it
+                                    TARGET_PATH=$(echo $armhf_noble_target_path | sed 's/\/$//')
                                 else # if arm64 (64-bit)
-                                    TARGET_PATH=$(echo $focal_target_path | sed 's/\/$//') # Last "/" is removed if there's any
+                                    TARGET_PATH=$(echo $noble_target_path | sed 's/\/$//') # Last "/" is removed if there's any
+                                fi
+                                ;;
+                            *)
+                                if [ "$SYSTEM_ARCH" != "aarch64" ] && [[ -v armhf_noble_target_path ]]; then # If armhf (32-bit) and has config for it
+                                    TARGET_PATH=$(echo $armhf_noble_target_path | sed 's/\/$//')
+                                else # if arm64 (64-bit)
+                                    TARGET_PATH=$(echo $noble_target_path | sed 's/\/$//') # Last "/" is removed if there's any
                                 fi
                                 ;;
                         esac
@@ -353,11 +374,18 @@ function validateInput
                                     TARGET_PATH=$(echo $focal_target_path | sed 's/\/$//') # Last "/" is removed if there's any
                                 fi
                                 ;;
-                            *)
-                                if [ "$SYSTEM_ARCH" != "aarch64" ] && [[ -v armhf_target_path ]]; then # If armhf (32-bit) and has config for it
-                                    TARGET_PATH=$(echo $armhf_focal_target_path | sed 's/\/$//')
+                            "24.04")
+                                if [ "$SYSTEM_ARCH" != "aarch64" ] && [[ -v armhf_noble_target_path ]]; then # If armhf (32-bit) and has config for it
+                                    TARGET_PATH=$(echo $armhf_noble_target_path | sed 's/\/$//')
                                 else # if arm64 (64-bit)
-                                    TARGET_PATH=$(echo $focal_target_path | sed 's/\/$//') # Last "/" is removed if there's any
+                                    TARGET_PATH=$(echo $noble_target_path | sed 's/\/$//') # Last "/" is removed if there's any
+                                fi
+                                ;;
+                            *)
+                                if [ "$SYSTEM_ARCH" != "aarch64" ] && [[ -v armhf_noble_target_path ]]; then # If armhf (32-bit) and has config for it
+                                    TARGET_PATH=$(echo $armhf_noble_target_path | sed 's/\/$//')
+                                else # if arm64 (64-bit)
+                                    TARGET_PATH=$(echo $noble_target_path | sed 's/\/$//') # Last "/" is removed if there's any
                                 fi
                                 ;;
                         esac
@@ -401,20 +429,23 @@ function runPostInstall
                 case "$SYSTEM_RELEASE_VERSION" in
                     "16.04") read -p "Instalation requires to run a command to take effect (Command: $post_install). Run now? (y/Y): " -r ;;
                     "20.04") read -p "Instalation requires to run a command to take effect (Command: $focal_post_install). Run now? (y/Y): " -r ;;
-                    *) read -p "Instalation requires to run a command to take effect (Command: $focal_post_install). Run now? (y/Y): " -r ;;
+                    "24.04") read -p "Instalation requires to run a command to take effect (Command: $noble_post_install). Run now? (y/Y): " -r ;;
+                    *) read -p "Instalation requires to run a command to take effect (Command: $noble_post_install). Run now? (y/Y): " -r ;;
                 esac
             fi
             if [ $SAY_YES_MODE -eq 1 ] || [[ $REPLY =~ ^[Yy]$ ]]; then
                 case "$SYSTEM_RELEASE_VERSION" in
                     "16.04") showVerbose "Running post instalation command '$post_install' " ;;
                     "20.04") showVerbose "Running post instalation command '$focal_post_install' " ;;
-                    *) showVerbose "Running post instalation command '$focal_post_install' " ;;
+                    "24.04") showVerbose "Running post instalation command '$noble_post_install' " ;;
+                    *) showVerbose "Running post instalation command '$noble_post_install' " ;;
                 esac
                 if [ $DEBUG_MODE -eq 0 ]; then
                     case "$SYSTEM_RELEASE_VERSION" in
                         "16.04") eval "$post_install" ;; #FIXME: Can be dangerous
                         "20.04") eval "$focal_post_install" ;; #FIXME: Can be dangerous
-                        *) eval "$focal_post_install" ;; #FIXME: Can be dangerous
+                        "24.04") eval "$noble_post_install" ;; #FIXME: Can be dangerous
+                        *) eval "$noble_post_install" ;; #FIXME: Can be dangerous
                     esac
                 fi
             fi
@@ -626,6 +657,23 @@ function backup_files
                 fi
 
                 return_code=$?
+
+                # Check if backup file failed and empty due to not enough space issue
+                checkFileIfEmpty $targetFilename
+                if [ $? -eq 1 ]; then
+                    showVerbose "Backup file '$targetFilename' is empty. There might not have enough space."
+
+                    # Delete backup file if it's empty
+                    showVerbose "Deleting $targetFilename because it's an empty file and a failed backup"
+                    if [ $RAN_AS_SUDO -eq 0 ]; then
+                        sudo -p "$PASSWORD_PROMPT" rm $targetFilename
+                    else
+                        rm $targetFilename
+                    fi
+
+                    return_code=1
+                    break
+                fi
             fi
         done
     else
@@ -750,16 +798,50 @@ function reset_path
         do
             sourceFilename=$file
             targetFilename=`echo $file | sed "s/"${BACKUP_SUFFIX}"*$//g"`
-            showVerbose "Restoring $sourceFilename as $targetFilename"
-            if [ $DEBUG_MODE -eq 0 ]; then
-                if [ $RAN_AS_SUDO -eq 0 ]; then
-                    sudo -p "$PASSWORD_PROMPT" mv $sourceFilename $targetFilename
-                else
-                    mv $sourceFilename $targetFilename
+
+            checkFileIfEmpty $sourceFilename
+
+            if [ $? -eq 1 ]; then
+                # Delete backup file if it's empty
+                showVerbose "Deleting $sourceFilename because it's an empty file and a failed backup"
+                if [ $DEBUG_MODE -eq 0 ]; then
+                    if [ $RAN_AS_SUDO -eq 0 ]; then
+                        sudo -p "$PASSWORD_PROMPT" rm $sourceFilename
+                    else
+                        rm $sourceFilename
+                    fi
+                    return_code=$?
                 fi
-                return_code=$?
+            else
+                showVerbose "Restoring $sourceFilename as $targetFilename"
+                if [ $DEBUG_MODE -eq 0 ]; then
+                    if [ $RAN_AS_SUDO -eq 0 ]; then
+                        sudo -p "$PASSWORD_PROMPT" mv $sourceFilename $targetFilename
+                    else
+                        mv $sourceFilename $targetFilename
+                    fi
+                    return_code=$?
+                fi
             fi
         done
+
+        # Delete empty backup files
+        if [ $? -eq 1 ]; then
+            for file in "${backupfiles_list[@]}"
+            do
+                deleteFilename=$file
+                showVerbose "Deleting $deleteFilename"
+                if [ $DEBUG_MODE -eq 0 ]; then
+                    if [ $RAN_AS_SUDO -eq 0 ]; then
+                        sudo -p "$PASSWORD_PROMPT" rm $deleteFilename
+                    else
+                        rm $deleteFilename
+                    fi
+
+                    return_code=$?
+                fi
+            done
+        fi
     fi
 
     return ${return_code}
@@ -786,6 +868,7 @@ CFG_FOLDER="components"
 case "$SYSTEM_RELEASE_VERSION" in
     "16.04") BLOCK_OTA_PKG="packages/BlockOTA.jerk" ;;
     "20.04") BLOCK_OTA_PKG="packages/BlockOTA_focal.jerk" ;;
+    "24.04") BLOCK_OTA_PKG="packages/BlockOTA_noble.jerk" ;;
     *) BLOCK_OTA_PKG="packages/BlockOTA_focal.jerk" ;;
 esac
 
@@ -802,6 +885,7 @@ if [ ! -f "$BLOCK_OTA_PKG" ]; then # Check if Block OTA package is in the same d
     case "$SYSTEM_RELEASE_VERSION" in
         "16.04") BLOCK_OTA_PKG="$XDG_DATA/jerk/packages/BlockOTA.jerk" ;;
         "20.04") BLOCK_OTA_PKG="$XDG_DATA/jerk/packages/BlockOTA_focal.jerk" ;;
+        "24.04") BLOCK_OTA_PKG="$XDG_DATA/jerk/packages/BlockOTA_noble.jerk" ;;
         *) BLOCK_OTA_PKG="$XDG_DATA/jerk/packages/BlockOTA.jerk" ;;
     esac
     if [ ! -f "$BLOCK_OTA_PKG" ]; then # Check if Block OTA package is installed in the standard home data directory
